// <auto-generated />
using System;
using System.Diagnostics.CodeAnalysis;
using Mailman.Services.Security;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Mailman.Services.Migrations.OAuth
{
    [DbContext(typeof(OAuthTokenContext))]
    [ExcludeFromCodeCoverage]
    partial class OAuthTokenContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065");

            modelBuilder.Entity("Mailman.Services.Security.TokenInfo", b =>
                {
                    b.Property<string>("Email")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(320);

                    b.Property<string>("AccessToken")
                        .IsRequired();

                    b.Property<DateTime>("ExpiryUtc");

                    b.Property<string>("RefreshToken");

                    b.HasKey("Email");

                    b.ToTable("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
