 export const REQUEST_MERGE_TEMPLATES = "REQUEST_MERGE_TEMPLATES";
 export const RECEIVE_MERGE_TEMPLATES = "RECEIVE_MERGE_TEMPLATES";

 export const FETCH_MERGE_TEMPLATES_REQUEST   = 'FETCH_MERGE_TEMPLATES_REQUEST';
 export const FETCH_MERGE_TEMPLATES_SUCCESS = 'FETCH_MERGE_TEMPLATES_SUCCESS';
 export const FETCH_MERGE_TEMPLATES_FAILURE = 'FETCH_MERGE_TEMPLATES_FAILURE';
 
